name = "ailiuliu"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[vars]


[[d1_databases]]
binding = "DB"
database_name = "your-database-name"
database_id = "your-database-id"
