name = "ailiuliu"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./build/client"

[vars]
MY_VAR = "Hello from Cloudflare"
API_BASE = ""
API_TOKEN = ""
CLERK_PUBLISHABLE_KEY = ""
CLERK_SECRET_KEY = ""
